name: Sync LeetCode

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs automatically every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run LeetCode Sync
        uses: jasonwryan/leetcode-sync@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          leetcode_session: ${{ secrets.LEETCODE_SESSION }}
          leetcode_csrf_token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
